name: cpp-linter

on: pull_request

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          extra-args: -std=c++98 -Wall -Wextra -Werror
          thread-comments: true
          step-summary: true

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1